### ISSUE TITLE
Missing Dragonkin Feats

### ISSUE THREAD

**Issue by TheChronoMaster** [TikaelSol/PF2e-Expansion-Pack#3]
Compared to the Pathfinder Infinite PDF:

The Dragonkin feats Draconic Scales, Energize Breath, Gold Sight, Draconic Deflection, Enhanced Armaments, Draconic Bulwark, Frightful Aura, and Draconic Transformation are not included.

**Comment by TikaelSol** [comment]
I have not asked Luis if releasing content from the PDF release is ok.  Before, I got permission to release what was on his blog so that is what is included in the module.  I will follow up on this when I have time but I will not have time to work on this module for several weeks given work that needs done on Animal Companions and the pf2e system itself (plus real life work).
